### ISSUE TITLE
Actividad 5 Práctica de Moprosoft

### ISSUE THREAD

**Issue by MLR062998** [SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-equipo-de-angeles#1]
[Actividad 5 Práctica de Moprosoft.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-practica-de-moprosoft-equipo-de-angeles/files/12826895/Actividad.5.Practica.de.Moprosoft.pdf)

**Comment by abicoronel** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
